server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
        default:
            max-concurrent-calls: 10
#            max-wait-duration: 100ms
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
#        enable-exponential-backoff: true
      default:
        max-attempts: 3
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
#  jackson:
#    default-property-inclusion: NON_NULL
#    serialization:
#      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/book
    user: root
    password: 1234
    baseline-on-migrate: true
    locations: classpath:db/migrations
springdoc:
  show-actuator: true