server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
#  jackson:
#    default-property-inclusion: NON_NULL
#    serialization:
#      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/book
    user: root
    password: 1234
    baseline-on-migrate: true
    locations: classpath:db/migrations